### ISSUE TITLE
US04 - Excluir Produtos

### ISSUE THREAD

**Issue by Bruno-Felix** [Bruno-Felix/REQ-2020.2-PetSpace#29]
## Descrição

Eu, como administrador gostaria de excluir um produto para retira-lo do site.
 
## Critérios de aceitação 

- [x] Deletar o produto em questão porém manter o histórico de venda.
- [x] Opção de excluir um produto permanentemente ou apenas desabilita-lo.

**Comment by marsicanogeorge** [comment]
Excluir, significa apagar todos os registros de um produto, ou apenas desabilitá-lo para que não esteja mais disponível para utilização?
Apagar um produto significa, apagar também, todos os registros de compras desse produto? Se for isso, vc perde todo o histórico.
Entendo que, deveriam ser estabelecidos critérios de aceitação (regras de negócio) mais claras para a deleção de um produto.
