### ISSUE TITLE
US05 - Usuário Visualizar a Lista de Produtos

### ISSUE THREAD

**Issue by Bruno-Felix** [Bruno-Felix/REQ-2020.2-PetSpace#30]
## Descrição

Eu, como usuário gostaria de visualizar a lista de produtos para que eu possa ver produtos disponíveis para compra.
 

## Critérios de aceitação 

- [x] Exibir nome, categoria, preço e descrição dos produtos.  
- [x] Lista ser ordenada por ordem do produto cadastrado mais recente.

**Comment by marsicanogeorge** [comment]
Critérios de Aceitação:
 - Quais são os dados que compõem a lista dos produtos para compra?
 - Como essa lista será exibida? (ordem alfabética, tipo de produto, ...)
 - Haverá algum parâmetro de ordenação dessa lista?
Responder a perguntas como essas levará vcs a terem os critérios de aceitação da história.
